[package]
name = "pulsar-embedded-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
log = "0.4.17"
pulsar = { path = "../../pulsar" }
pulsar-core = { path = "../../pulsar-core" }
tokio = { version = "1", features = ["full"] }
