[package]
name = "validatron-derive"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true
# Disable tests until https://github.com/Exein-io/pulsar/issues/3 is fixed
test = false

[dependencies]
syn = { version = "1.0" }
quote = "1.0"
proc-macro2 = "1.0"
