[package]
name = "xtask"
version = "0.4.0"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
clap = { version = "4.1.1", features = ["derive"] }
xshell = "0.2.2"
