[package]
name = "xtask"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.58"
clap = { version = "4.1.1", features = ["derive"] }
xshell = "0.2.2"
