[package]
name = "validatron"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
log = "0.4.17"
thiserror = "1.0.40"
validatron-derive = {path = "derive"}
