[package]
name = "smtp-notifier"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
pulsar-core = { workspace = true }

anyhow = { workspace = true }
lettre = { workspace = true, features = [
    "smtp-transport",
    "tokio1-native-tls",
    "tokio1",
    "builder",
    "serde",
] }
openssl = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
leon = { workspace = true }
nix = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }

[features]
default = ["openssl"]
tls-openssl = ["openssl", "lettre/tokio1-native-tls"]
tls-rustls = ["lettre/tokio1-rustls-tls"]
openssl-vendored = ["openssl?/vendored"]

[dev-dependencies]
toml = { workspace = true }
