[package]
name = "logger"
version = "0.4.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
pulsar-core = { path = "../../pulsar-core" }
bpf-common = { path = "../../bpf-common" }

tokio = { version = "1", features = ["full"] }
log = "0.4"
bytes = "1.1"
chrono = "0.4.23"
