[package]
name = "file-system-monitor"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[features]
test-suite = ["bpf-common/test-utils"]

[dependencies]
bpf-common = { workspace = true }
pulsar-core = { workspace = true }

nix = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
log = { workspace = true }

[build-dependencies]
bpf-builder = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
