# Title: GRUB Configuration File Creation

# Creation date: 2025/04/14

# MITRE ATT&CK Tactic: TA0003 - Persistence - https://attack.mitre.org/tactics/TA0003/

# MITRE ATT&CK Technique: T1542 - Pre-OS Boot - https://attack.mitre.org/techniques/T1542/

- name: Modification of GRUB Configuration Files
  type: FileCreated
  category: persistence
  severity: medium
  description: Detects the creation or modification of GRUB configuration files that define boot behavior. 
    Unauthorized changes to these files can allow attackers to hijack the boot process or gain persistence. 
    Adversaries may alter GRUB settings to execute malicious payloads before the operating system fully loads.
  condition: (
    payload.filename STARTS_WITH "/etc/default/grub.d/" OR
    payload.filename STARTS_WITH "/etc/default/grub" OR
    payload.filename STARTS_WITH "/etc/grub.d/" OR
    payload.filename STARTS_WITH "/boot/grub2/grub.cfg" OR
    payload.filename STARTS_WITH "/boot/grub/grub.cfg" OR
    payload.filename STARTS_WITH "/boot/efi/EFI//grub.cfg" OR
    payload.filename STARTS_WITH "/etc/sysconfig/grub"
    ) AND NOT (
      header.image IN [
        "/bin/dpkg", "/usr/bin/dpkg", "/bin/dockerd", "/usr/bin/dockerd", "/usr/sbin/dockerd", "/bin/microdnf",
        "/usr/bin/microdnf", "/bin/rpm", "/usr/bin/rpm", "/bin/snapd", "/usr/bin/snapd", "/bin/yum", "/usr/bin/yum",
        "/bin/dnf", "/usr/bin/dnf", "/bin/podman", "/usr/bin/podman", "/bin/dnf-automatic", "/usr/bin/dnf-automatic",
        "/bin/pacman", "/usr/bin/pacman", "/usr/bin/dpkg-divert", "/bin/dpkg-divert", "/sbin/apk", "/usr/sbin/apk",
        "/usr/local/sbin/apk", "/usr/bin/apt", "/usr/sbin/pacman", "/bin/podman", "/usr/bin/podman", "/usr/bin/puppet",
        "/bin/puppet", "/opt/puppetlabs/puppet/bin/puppet", "/usr/bin/chef-client", "/bin/chef-client",
        "/bin/autossl_check", "/usr/bin/autossl_check", "/proc/self/exe", "/dev/fd/",  "/usr/bin/pamac-daemon",
        "/bin/pamac-daemon", "/usr/lib/snapd/snapd", "/usr/local/bin/dockerd", "/usr/bin/crio", "/usr/sbin/crond",
        "/opt/puppetlabs/puppet/bin/ruby", "/usr/libexec/platform-python", "/kaniko/kaniko-executor",
        "/usr/local/bin/dockerd", "/usr/bin/podman", "/bin/install", "/proc/self/exe", "/usr/lib/systemd/systemd",
        "/usr/sbin/sshd", "/usr/bin/gitlab-runner", "/opt/gitlab/embedded/bin/ruby", "/usr/sbin/gdm", "/usr/bin/install",
        "/usr/local/manageengine/uems_agent/bin/dcregister", "/usr/local/bin/pacman"
      ] OR
      payload.filename STARTS_WITH "/nix/store/" OR
      payload.filename STARTS_WITH "/var/lib/dpkg/" OR
      payload.filename STARTS_WITH "/tmp/vmis." OR
      payload.filename STARTS_WITH "/snap/" OR
      payload.filename STARTS_WITH "/dev/fd/" OR
      payload.filename STARTS_WITH "/usr/lib/virtualbox/" OR
      payload.filename ENDS_WITH "swp" OR
      payload.filename ENDS_WITH "swpx" OR
      payload.filename ENDS_WITH "swx" OR
      payload.filename ENDS_WITH "dpkg-remove" OR
      header.image STARTS_WITH "sed" AND payload.filename STARTS_WITH "sed"
    )
