[alias]
xtask = "run --package xtask --"

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C",
  "linker=clang",
  "-C",
  "link-arg=-fuse-ld=lld",
  "-C",
  "link-arg=--target=x86_64-unknown-linux-gnu"
]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C",
  "linker=clang",
  "-C",
  "link-arg=-fuse-ld=lld",
  "-C",
  "link-arg=--target=x86_64-unknown-linux-musl"
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C",
  "linker=clang",
  "-C",
  "link-arg=-fuse-ld=lld",
  "-C",
  "link-arg=--target=aarch64-unknown-linux-gnu"
]

[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C",
  "linker=clang",
  "-C",
  "link-arg=-fuse-ld=lld",
  "-C",
  "link-arg=--target=aarch64-unknown-linux-musl"
]

[target.riscv64gc-unknown-linux-gnu]
rustflags = [
  "-C",
  "linker=clang",
  "-C",
  "link-arg=-fuse-ld=lld",
  "-C",
  "link-arg=--target=riscv64-unknown-linux-gnu"
]
