# Title: SSHD Config Tampering

# Creation Date: 09/04/2025

# MITRE ATT&CK Tactics: T0006 - Credential Access - https://attack.mitre.org/tactics/TA0006/

# MITRE ATT&CK Technique: T1098 - Account Manipulation - https://attack.mitre.org/techniques/T1098/
### PERSISTENCE o CREDENTIAL ACCESS
- name: SSHD config modification
  type: FileOpened
  category: credential_access
  severity: high
  description: Detects changes to /etc/ssh/sshd_config, which may indicate attempts to bypass authentication controls or enable unauthorized access.
  condition: payload.filename STARTS_WITH "/etc/ssh/sshd_config" AND payload.flags CONTAINS "O_WRONLY"





