name: 'Install cross'
description: 'Install cross-rs from its latest release'

runs:
  using: composite
  steps:
    - name: Install cross
      shell: bash
      run: |
        cargo install cross --git https://github.com/cross-rs/cross

    - run: cross --version --verbose
      shell: bash
