[package]
name = "pulsar-module-as-library"
version = "0.1.0"
edition = "2021"

[dependencies]
network-monitor = { path = "../../crates/modules/network-monitor" }
bpf-common = { path = "../../crates/bpf-common" }
tokio = { version = "1", features = ["full"] }
