name: "Audit Dependencies"
on:
  # Run manually
  workflow_dispatch:

permissions: read-all

jobs:
  audit:
    name: Audit Rust Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Audit
        run: nix develop --command cargo audit
