name: Build
on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build (${{ matrix.profile }}, ${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile:
          - dev
          - release
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - riscv64gc-unknown-linux-gnu
          - riscv64gc-unknown-linux-musl

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Build
        run: nix develop --command just build ${{ matrix.target }} ${{ matrix.profile }}

      - name: Check build did not modify any files
        run: |
          CHANGES=$(git status --porcelain)
          if [ -n "$CHANGES" ]; then
            echo "Changes detected:"
            git diff
          fi
          test -z "$CHANGES"

      - name: Unit tests
        run: nix develop --command just test ${{ matrix.target }}
