name: Integration tests
on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile:
          - debug
          - release

        # For `musl` builds, use the `all-vendored` and `tls-rustls` features.
        platform:
          - target: x86_64-unknown-linux-musl
            args: "--no-default-features --features full --features all-vendored --features tls-rustls"
            kernel-versions: "5.13,5.15,6.0,6.3,6.6"

          - target: aarch64-unknown-linux-musl
            args: "--no-default-features --features full --features all-vendored --features tls-rustls"
            kernel-versions: "5.15,6.2,6.6"

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        if: endsWith(matrix.platform.target, 'musl')
        run: |
          sudo apt install -y qemu-system

      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.platform.target }}

      - name: Install cross
        uses: ./.github/actions/install-cross

      - name: Integration tests
        if: endsWith(matrix.platform.target, 'musl')
        run: |
            cargo xtask test \
                --force-architest \
                --target=${{ matrix.platform.target }} \
                --kernel-versions=${{ matrix.platform.kernel-versions }} \
                --features all-vendored --features tls-rustls
