name: Quality Checks
on:
  pull_request:
    branches:
      - "*"

jobs:
  lychee-link-check:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Link Checker
        run: nix develop --command bash -c 'lychee --no-progress $(git ls-files "*.md")'

  fmt:
    name: Formatting (rustfmt)
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Formatting (rustfmt)
        run: nix develop --command just fmt-check

  lint:
    name: Lint (clippy, ${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - riscv64gc-unknown-linux-gnu
          - riscv64gc-unknown-linux-musl

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Clippy (all crates)
        run: nix develop --command just clippy ${{ matrix.target }}

      - name: Check build did not modify any files
        run: test -z "$(git status --porcelain)"
