[package]
name = "pulsar-extension-module-example"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
pulsar = { path = "../.." }
pulsar-core = { path = "../../crates/pulsar-core" }
tokio = { version = "1", features = ["full"] }
