[package]
name = "pulsar-extension-module"
version = "0.1.0"
edition = "2021"

[dependencies]
pulsar = { path = "../../pulsar" }
pulsar-core = { path = "../../pulsar-core" }
tokio = { version = "1", features = ["full"] }
